version: '3.4'

services:
  api:
    image: kaykybc/rest-api-go:dev
    container_name: go_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: mysql
    container_name: go_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha12345
      MYSQL_DATABASE: go_api
    ports:
      - 3306:3306
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/



